
[Bulb.Lamp1]
name="Lamp1"
state="on"
bri=0.569
xy=[0.4957,0.3760]

[Bulb.Lamp2]
name="Lamp2"
state="on"
bri=0.882
xy=[0.5306,0.3479]

[Bulb.Lamp3]
name="Lamp3"
state="on"
bri=0.380
xy=[0.3171,0.2512]
