[Hub.Hub1]
name="Hub1"
ipaddr="192.168.11.17"
key="VHQitrMnCUvVb4YLmuTmYQvO54ZjUgihgSJGKTFy"

[Hub.Hub2]
name="Hub2"
ipaddr="192.168.11.50"
key="78g2lrMNHZHZFozjDJ7z7lneQhl8guZpzssU0HIr"


[Bulb.Lamp1]
name="Lamp1"
hubname="Hub1"
idh=29

[Bulb.Lamp2]
name="Lamp2"
hubname="Hub2"
idh=35

[Bulb.Lamp3]
name="Lamp3"
hubname="Hub2"
idh=36

